const char *mqtt_aws_uri = "mqtts://a52peqbfn4vsr-ats.iot.eu-north-1.amazonaws.com";
const char *mqtt_client_id = "basicPubSub";

const char *mqtt_root_ca_cert = "-----BEGIN CERTIFICATE-----\n"
                                "MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\n"
                                "ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\n"
                                "b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL\n"
                                "MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv\n"
                                "b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj\n"
                                "ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM\n"
                                "9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw\n"
                                "IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6\n"
                                "VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L\n"
                                "93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm\n"
                                "jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\n"
                                "AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA\n"
                                "A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI\n"
                                "U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs\n"
                                "N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv\n"
                                "o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU\n"
                                "5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy\n"
                                "rqXRfboQnoZsG4q5WTP468SQvvG5\n"
                                "-----END CERTIFICATE-----\n";

const char *mqtt_cert = "-----BEGIN CERTIFICATE-----\n"
                        "MIIDWTCCAkGgAwIBAgIUWWUaWBbAJp52du8C+H+qslvni0MwDQYJKoZIhvcNAQEL\n"
                        "BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g\n"
                        "SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTI0MDUwNjE3NTQ1\n"
                        "MVoXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0\n"
                        "ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKJO6a98EKgcbMQtyjM9\n"
                        "gBb2F1Gg3NMMJQCcS04yUEZDVO9Y1SFdPUvX/UZjn3gBww0NK7IlOUuDTKCayhJx\n"
                        "IinPTP8gBDDUpYe2DXiJimgzCbb3CIT66TRFVNva2XyWW8JWHbIkVf1o0K0ACewh\n"
                        "oWnCEpAO99tchLztJa979IFLtHuP29c2m0h1tO/aY8goOysqvXaWdofJ+cTAtdSL\n"
                        "cEJOYCM6s9Itbu3wc3jOa1oWC534FM/kNlpi8z7a1JswKevKGZH4Mlx4G+pli0QR\n"
                        "UoTzFC7zsb3/gYw3Geno+T8FZQj2G0BHtIOYC+xYF3HMJwKpZjPDuO8RGffo9PZ1\n"
                        "0qUCAwEAAaNgMF4wHwYDVR0jBBgwFoAUvWUR5zlZXXA30nyFs9W74ajgX0kwHQYD\n"
                        "VR0OBBYEFLnycysPShi/+WOeKs7w5wcOkiulMAwGA1UdEwEB/wQCMAAwDgYDVR0P\n"
                        "AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQAzSMqSiwunTJT367NZH40gIeDi\n"
                        "XyuIlaDuTxokVU+ZxQKbPPZHafUg1Ehy2rzVkdsh12sHqHh8ynH25GPvo5B4Q0ID\n"
                        "Ua+yqN8leM3rSh43i7vFSctJWhKITqzVP5I5x+AK5T7eVrH8cnWO+SRb8o/AhGjB\n"
                        "NF3SGH2TGd1AOvKQZ+8GmT62kxy4CDoPmWClKbADaInA8B5IuWhlMKCR+5HQO37a\n"
                        "+Q/IGbsZBNMGh22+ofEnLRtCDtM11LaOL6WrDA2gQrT2rCdgTI/X+ODpM/2bO1z9\n"
                        "c7UJOuMD297vzEu6JL2QfadA2Sjh6pCnUdDTj1Uh+qA+qaw0GfEhWi15YdTr\n"
                        "-----END CERTIFICATE-----\n";

const char *mqtt_privkey = "-----BEGIN RSA PRIVATE KEY-----\n"
                           "MIIEogIBAAKCAQEAok7pr3wQqBxsxC3KMz2AFvYXUaDc0wwlAJxLTjJQRkNU71jV\n"
                           "IV09S9f9RmOfeAHDDQ0rsiU5S4NMoJrKEnEiKc9M/yAEMNSlh7YNeImKaDMJtvcI\n"
                           "hPrpNEVU29rZfJZbwlYdsiRV/WjQrQAJ7CGhacISkA7321yEvO0lr3v0gUu0e4/b\n"
                           "1zabSHW079pjyCg7Kyq9dpZ2h8n5xMC11ItwQk5gIzqz0i1u7fBzeM5rWhYLnfgU\n"
                           "z+Q2WmLzPtrUmzAp68oZkfgyXHgb6mWLRBFShPMULvOxvf+BjDcZ6ej5PwVlCPYb\n"
                           "QEe0g5gL7FgXccwnAqlmM8O47xEZ9+j09nXSpQIDAQABAoIBAG6cpuc//r4CuSEt\n"
                           "L4qiFAQR7CxmG3f84865tRxyb4Ci7GQ9PuqA94ATj3kD9a68TKg9XJUIhzZuIa+m\n"
                           "LaZJ0YV60DdiI1j/4ltNd3q5CUkf1zQIwJaXxIwp374BNIySj7AuLgi0eKG9Z9Eu\n"
                           "oJR7CtzfNPVWLhYhxBhY6YDhUe02i2CmLVnBq3h3kfeCDbAe/9/uiA5VdRwSxfI/\n"
                           "OC+FKlOm9GOHYwOIjFXvmmC2C0ObZfl185ibGuxsIn04MO/d5tlcT8xH4nBbQsyB\n"
                           "zg68FwN59nU3ATAN7N5Zm9cw5iZbDzrZTNyAo14qEIsYXjYTUEy02m/SZgdkl26w\n"
                           "vlA3zSECgYEA15cAGszNfehEelVQwMD3C+Jex6QByPOaJIdYoWtX5nhqC8Cxsz/B\n"
                           "CjrwlvJGWgNgNPTONdrO9tuELTJmBavb58sUerlGdGmd5EHuApd58gw8UIYd51fW\n"
                           "Y/62kHrzgWwhGL/u23gC/hNHXfyJRf7/YyYTFiAXiDoU8RwyGqGbQYkCgYEAwLs2\n"
                           "/EeC+bM9hWurIeaaUsmg3ODlWcy0BRsrY4jN9byn0ZIX4zPeQa+/95PvkTY1Bi2n\n"
                           "pM+GLc3fGFmIqB5jZFVvfDBC08edAyCYt8T3xqNLszsqaa4bDkUoe89gDJdwsgaG\n"
                           "V6ItegPcbDh4eOx7tw/6TDigZplDLAsk3oh5TT0CgYAEVe8UmuXPEGrAIxMarUbK\n"
                           "oGTTkwLOLcf90BMCPAxqgCVx0xA/0JprQEAyaPDtQoAe0IWNI7dh04xW9FqE5q3n\n"
                           "fXgN98fo827Pdlv5BV7YdVKJNAlJ68ROAoNdaHuZMLmBq+p703AL+AtJYpjIJZax\n"
                           "QcTEfyS6AqEFMFH5oyJiMQKBgB7BQUL8vl/ORHD3/3UHcXToi+zzTmYIDmoKLeBS\n"
                           "QluGYVlF8N3mtv7QZtfBGaeYeNmli2z3WLgSdBlUoEQDpWSrZYDxypg08E9Bcl1Q\n"
                           "5yEhicDuHhSDHfom+xDWxML9n5QpCmMNlCg2WYRDdqYFRrCtsglbt+znZBqxJI8G\n"
                           "RCUZAoGAbsynYEKQ9lqw0M4H82yvPHHOO3vsleRX34arA+23fIZ9UfTbFjEqxs/r\n"
                           "7ce1eeh+/YdqfR8hnBLN8AUlIDaUh/fiRtie8e4kmYzvZMy13mGbO1FD+/hebsSW\n"
                           "eNBfJFkxnwLqmU3jQ/hIySfgLrXNUarxBIuI7IAC1y05ucR9iTQ=\n"
                           "-----END RSA PRIVATE KEY-----\n";